#ifndef MJPEG_DEFINE_H
#define MJPEG_DEFINE_H

//full screen flag
#define MJPEG_FULL_SCREEN   0x1
#define MJPEG_SCREEN_CLEAR  0x2
#define MJPEG_PREVIEW       0x4

//task event
//#define MJPEG_DATAIO_EVENT_LOAD_DATA    0x1
#define MJPEG_DATAIO_EVENT_LOAD_AUDIO_DATA    0x01
#define MJPEG_DATAIO_EVENT_STOP         0x02
#define MJPEG_DATAIO_EVENT_SHIFT        0x04
#define MJPEG_DATAIO_EVENT_PLAY_VIDEO   0x08
#define MJPEG_DATAIO_EVENT_LOAD_VIDEO_DATA    0x10


#define MJPEG_READ_EVENT_LOAD_AUDIO_DATA    0x01
#define MJPEG_READ_EVENT_LOAD_VIDEO_DATA    0x02
#define MJPEG_READ_EVENT_LOAD_AUDIO_DATA_FINISH    0x04
#define MJPEG_READ_EVENT_LOAD_VIDEO_DATA_FINISH    0x08

#define MJPEG_AUDIO_ENABLE 1
//index
enum 
{
    MJPEG_AVI = 0,
    MJPEG_MOV,
    MJPEG_MAX_COUNT,
};

//mode
enum
{
    MJPEG_IDEL_MODE = 0,
    MJPEG_PLAY_MODE,
};


//command
enum
{
    CMD_NULL = 0,
    CMD_DECODE_FIRST_FRAME,
    CMD_NORMAL_FORWARD,
    CMD_PAUSE,
    CMD_FORWARD,
    CMD_BACKWARD,
};

//msg
typedef enum
{
    MSG_FILE_READ_FAIL = -10,
    MSG_BUF_OVERFLOW,
    MSG_GENERAL_FAIL,
    MSG_CMD_ERROR,
    MSG_INPUT_ERROR,
    MSG_NOT_SUPPORT_FORMAT,
    MSG_MOV_TAG_SEARCH_FAIL,
    MSG_AVI_TAG_SEARCH_FAIL,
    MSG_JPEG_TAG_SEARCH_FAIL,
    MSG_JPEG_DECODE_FAIL,
    MSG_NO_ERR,
}E_MJPEG_MSG_T;

// state
typedef enum
{
    MJPEG_STATE_NULL = 0,
    MJPEG_STATE_PAUSE,
	MJPEG_STATE_PLAY	
}E_MJPEG_STATE_T;
#endif

