#ifndef _NETCONST_H
#define _NETCONST_H

enum {
    WIFI_USB_DEVICE_NONE,
	WIFI_USB_DEVICE_AR2524,
	WIFI_USB_DEVICE_RT73,
    WIFI_USB_DEVICE_RTL8711,
	WIFI_USB_DEVICE_RTL8192U,
	WIFI_USB_DEVICE_AR9271,
	ETHERNET_USB_DEVICE_DM9621,
    WIFI_USB_DEVICE_RTL8188C,
    WIFI_USB_DEVICE_RTL8188E,
    WIFI_USB_DEVICE_RTL8188EUS = WIFI_USB_DEVICE_RTL8188E,
    WIFI_USB_DEVICE_MAX,
};

#endif	/* _NETCONST_H */

