include ../../../config.mak

TARGET = $(LIB)libsystem.a

CC = $(BIN)gcc
CC_OPTION += -march=r3000 -c -mno-abicalls -O2 -fno-strict-aliasing -G 8 -I$(INC) -I$(G_INC) -DBOOT_ROM_TYPE -Wa,-ahl=
#CC_OPTION += -march=r3000 -c -mno-abicalls -O1 -g -G 8 -I$(INC) -I$(G_INC) -DBOOT_ROM_TYPE -Wa,-ahl=


AS = $(BIN)as
AS_OPTION = -march=r3000 -I$(INC) -I$(G_INC) -ahl=

LD = $(BIN)ld

AR = $(BIN)ar

S_OBJS =

C_OBJS = $(OBJ)SystemConfig.o $(OBJ)SystemMemory.o $(OBJ)SystemUsbCtrl.o $(OBJ)SystemDrive.o \
		$(OBJ)global612.o $(OBJ)ISP_Nand.o $(OBJ)ISP_Nor.o \
		$(OBJ)ISP_SPI.o $(OBJ)ISP_SD.o \
		$(OBJ)McardDevInfo.o \
# $(OBJ)SetTabFunc.o  $(OBJ)flashrep.o $(OBJ)ISP_None.o $(OBJ)SystemPM.o

ALL_OBJS =  $(C_OBJS)

all: $(TARGET)

$(TARGET)	: $(ALL_OBJS)
	$(AR) -rsv $(TARGET) $(ALL_OBJS)

$(S_OBJS):	$(OBJ)%.o: $(SRC)%.s makefile
	$(AS) $(AS_OPTION)$(@:.o=.lst) -o $@ $<

$(C_OBJS):	$(OBJ)%.o: $(SRC)%.c makefile
	$(CC) $(CC_OPTION)$(@:.o=.lst) -o $@ $<

clean:
	rm -f $(TARGET) $(ALL_OBJS) $(OBJ)\*.lst $(SRC)\*.bak
