#ifndef __BASIC_ENUM_H__
#define __BASIC_ENUM_H__


typedef enum  _WHILE_CACHE_MISS_DO
{
	WHILE_CACHE_MISS_DO_ADD,
	WHILE_CACHE_MISS_DO_IGNORE,
} WHILE_CACHE_MISS_DO;

typedef enum  _CACHE_SPACE_STYLE
{
	CACHE_SPACE_STYLE_RANDOM,
	CACHE_SPACE_STYLE_STATIC_ALLOCATED,
} CACHE_SPACE_STYLE;


//Result enum
typedef enum  _CACHE_MANAGER_FUNC_RESULT
{
	//SUCCESSFUL
	CACHE_MANAGER_FUNC_RESULT_SUCCESSFUL = 0x0,
	//ERROR
	CACHE_MANAGER_FUNC_RESULT_ERROR = 0xFF,
	CACHE_MANAGER_FUNC_RESULT_ERROR_CACHE_NULL = 0x1
} CACHE_MANAGER_FUNC_RESULT;



typedef enum  MEASURE_MODE_
{
  MEASURE_MODE_STRING = 0,
  MEASURE_MODE_RECTANGLE_FILLED
} MEASURE_MODE;


typedef enum  GLYPH_SET_MODE_
{
  GLYPH_SET_MODE_GLYPH = 0,
  GLYPH_SET_MODE_DELIMITER,
  GLYPH_SET_MODE_WHOLESTRING
} GLYPH_SET_MODE;

typedef enum  ORIGIN_MODE_
{
  ORIGIN_MODE_BASE = 0,
  ORIGIN_MODE_CORNER_LEFTUP
} ORIGIN_MODE;

typedef enum  COORDINATE_ORIGIN_MODE_
{
  COORDINATE_ORIGIN_MODE_IMAGE_PLANE = 0,
  COORDINATE_ORIGIN_MODE_PRINT_REGION
} COORDINATE_ORIGIN_MODE;


typedef enum  PRINT_POS_MODE_
{
  PRINT_POS_MODE_UP_LEFT = 0,
  PRINT_POS_MODE_BASELINE
} PRINT_POS_MODE;


typedef enum  PRINT_REGION_MODE_
{
  PRINT_REGION_MODE_IMAGE_PLANE = 0,
  PRINT_REGION_MODE_PRINT_REGION
} PRINT_REGION_MODE;


typedef enum  CHANGE_LINE_X_ALIGN_MODE_
{
  CHANGE_LINE_X_ALIGN_MODE_FIRST_LINE = 0,
  CHANGE_LINE_X_ALIGN_MODE_PRINT_REGION,
  CHANGE_LINE_X_ALIGN_MODE_SPECIFIED_X
} CHANGE_LINE_X_ALIGN_MODE;

typedef enum  Font_DATA_AT_
{
  FONT_DATA_AT_MEMORY = 0,
  FONT_DATA_AT_FILE,
} FONT_DATA_AT;

typedef enum  DISPLAY_MODE_
{
  DISPLAY_MODE_YYCBCR = 0,
  DISPLAY_MODE_RGB
} DISPLAY_MODE;

typedef enum  COLOR_FORMAT_
{
  COLOR_FORMAT_YYCBCR = 0,
  COLOR_FORMAT_RGB
} COLOR_FORMAT;



typedef enum  NOT_DRAW_OVER_BORDER_
{
	NOT_DRAW_OVER_BORDER_TOP    = 0x1,
	NOT_DRAW_OVER_BORDER_BOTTOM = 0x2,
	NOT_DRAW_OVER_BORDER_LEFT   = 0x4,
	NOT_DRAW_OVER_BORDER_RIGHT  = 0x8
} NOT_DRAW_OVER_BORDER;


#endif //__BASIC_ENUM_H__

