#ifndef __ML_StringDefine_H__
#define __ML_StringDefine_H__

enum{
	String_Yes	= 1,					// 1  
	String_No,							// 2  
	String_On,							// 3  
	String_Off, 						// 4  
	String_All, 						// 5  
	String_FullScreen,					// 6  
	String_ImageSize,					// 7  
	String_PhotoTransition, 			// 8  
	String_SlideShowEffect, 			// 9  
	String_SlideShowSpeed,				// 10 
	String_SlideShowShuffle,			// 11 
	String_SlideShowRepeat, 			// 12 
	String_Fade,						// 13 
	String_Shutter, 					// 14 
	String_CrossComb,					// 15 
	String_Mask,						// 16 
	String_Brick,						// 17 
	String_Dissolve,					// 18 
	String_Bar, 						// 19 
	String_Expansion,					// 20 
	String_Silk,						// 21 
	String_Sketch,						// 22 
	String_Grid,						// 23 
	String_Scroll,						// 24 
	String_KenBurns,					// 25 
	String_BullentinBoard,				// 26 
	String_3DCube,						// 27 
	String_3DFlip,						// 28 
	String_3DSwap,						// 29 
	String_Push,						// 30 
	String_MultiEffect, 				// 31 
	String_Random,						// 32 
	String_Fast,						// 33 
	String_Normal,						// 34 
	String_Slow,						// 35 
	String_VideoRepeat, 				// 36 
	String_VideoSettings,				// 37 
	String_MusicRepeat, 				// 38 
	String_LanguageName, 	            // 39 
	String_CopyFile,					// 40 
	String_DeleteFile,					// 41 
	String_Rotate,						// 42 
	String_Zoom,						// 43 
	String_StartSlideShow,				// 44 
	String_ResetSettings,				// 45 
	String_SystemSettings,				// 46 
	String_SaveSetup,					// 47 
	String_PCPrinterSideMonitor,		// 48 
	String_ConnecttoPC, 				// 49 
	String_ConnecttoPrinter,			// 50 
	String_DisplayChroma,				// 51 
	String_BrightnessContrast,			// 52 
	String_SaturationHue,				// 53 
	String_ColorManagement, 			// 54 
	String_OutputSelect,				// 55 
	String_Refresh, 					// 56 
	String_ShowDeviceBase,				// 57 
	String_DeleteDevice,				// 58 
	String_Connect, 					// 59 
	String_ServiceSearch,				// 60 
	String_MatchDevice, 				// 61 
	String_A2DPConnect, 				// 62 
	String_A2DPDisonnect,				// 63 
	String_A2DPConfig,					// 64 
	String_Hint,						// 65 
	String_OPushHint,					// 66 
	String_OPushDisconnect, 			// 67 
	String_TransferFile,				// 68 
	String_FormatNand,					// 69 
	String_BlueTooth,					// 70 
	String_FTPCHint,					// 71 
	String_FTPSHint,					// 72 
	String_A2DPHint,					// 73 
	String_FTPCDisconnect,				// 74 
	String_FTPSDisconnect,				// 75 
	String_A2DPDisconnect,				// 76 
	String_FTPPullFolder,				// 77 
	String_FTPSetFolderForward, 		// 78 
	String_FTPSetFolderBackup,			// 79 
	String_FTPSetFolderRoot,			// 80 
	String_FTPCreateFolder, 			// 81 
	String_FTPPullFile, 				// 82 
	String_FTPPush, 					// 83 
	String_FTPdelete,					// 84 
	String_SetFavorite, 				// 85 
	String_SeparateWindows, 			// 86 
	String_VideoForwardSecond,			// 87 
	String_Areyousure,					// 88 
	String_RotateFull,					// 89 
	String_Default, 					// 90 
	String_One, 						// 91 
	String_Optimal60,					// 92 
	String_Optimal70,					// 93 
	String_Optimal80,					// 94 
	String_Optimal90,					// 95 
	String_Sharp,						// 96 
	String_BlackWhite,					// 97 
	String_SEBIAN,						// 98 
	String_ColorMix,					// 99 
	String_Blur,						// 100
	String_Disable, 					// 101
	String_Opushtransferinit,			// 102
	String_FTPCConnect, 				// 103
	String_FTPSConnect, 				// 104
	String_Red, 						// 105
	String_Skin,						// 106
	String_Yellow,						// 107
	String_Green,						// 108
	String_Cyan,						// 109
	String_Blue,						// 110
	String_Magenta, 					// 111
	String_SystemInfo,					// 112
	String_FileSortByNameAscend,		// 113
	String_FileSortByNameDescend,		// 114
	String_FileSortByDateAscend,		// 115
	String_FileSortByDateDescend,		// 116
	String_FileSortBySizeAscend,		// 117
	String_FileSortBySizeDescend,		// 118
	String_Original,					// 119
	String_Shuffle, 					// 120
	String_SpecialEffect,				// 121
	String_PrintPhoto,					// 122
	String_DynamicSelect,				// 123
	String_SearchDevice,				// 124
	String_AVService,					// 125
	String_Setting, 					// 126
	String_TVNTSC,						// 127
	String_TVPAL,						// 128
	String_HDTV1080i,					// 129
	String_HDTV720p,					// 130
	String_SVideo,						// 131
	String_DSub,						// 132
	String_Panel,						// 133
	String_2,							// 134
	String_4,							// 135
	String_8,							// 136
	String_16,							// 137
	String_32,							// 138
	String_Done,						// 139
	String_TargetInvalid,				// 140
	String_Fail,						// 141
	String_DiskFull,					// 142
	String_FileNotFound,				// 143
	String_TargetReadOnly,				// 144
	String_Cancel,						// 145
	String_RedEyesRemove,				// 146
	String_FaceDetection,				// 147
	String_PRODUCT_MODEL,				// 148
	String_PRODUCT_FW_VERSION,			// 149
	String_MyFavor, 					// 150
	String_MyFavor1AddFile, 			// 151
	String_MyFavor2AddFile, 			// 152
	String_MyFavor3AddFile, 			// 153
	String_MyFavor4AddFile, 			// 154
	String_MyFavorReset1,				// 155
	String_MyFavorReset2,				// 156
	String_MyFavorReset3,				// 157
	String_MyFavorReset4,				// 158
	String_MyFavorDelete,				// 159
	String_ConnecttoSideMonitor,		// 160
	String_DynamicLighting,		        // 161
	String_MusicLyric,                  // 162
	String_GBK,                         // 163
	String_BIG5,                        // 164
	String_UNICODE,                     // 165
	String_FileSortByEXIFDateAscend,    // 166
	String_FileSortByEXIFDateDescend,   // 167
	String_NULL,						// 168
}; // 1-1 match with SetupString.c's BYTE *Str_English[String_NULL]=


/* actually, (String_NULL + 1) entries in this array to match the above String_NULL enumeration */


extern BYTE *Str_Multi[String_NULL+1];
extern BYTE *Str_English[String_NULL+1];

#endif 

